services:
  app:
    build: { context: ., dockerfile: Dockerfile }
    command: sleep infinity
    privileged: true
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    volumes: ["data-dynamodb:/data"]
volumes:
  data-dynamodb: