default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>

development:
  <<: *default
  database: esoteric_word_development

test:
  <<: *default
  database: esoteric_word_test

production:
  <<: *default
  database: esoteric_word_production
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["MYSQL_ADMIN_USER"] %>
  password: <%= ENV["MYSQL_ADMIN_PASSWORD"] %>
